version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - run: yarn
      - run: yarn deploy:ci

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
                branches:
                  only:
                    - master
